### ISSUE TITLE
Error en el archivo BankAccount de Entities

### ISSUE THREAD

**Issue by LuigimonSoft** [EcommerceBBVA/BBVA-CSHARP#1]
Hay un error en el archivo BankAccount en la linea:

`[JsonProperty(PropertyName = "alias, NullValueHandling=NullValueHandling.Ignore")]
public String Alias { get; set; }`

y deberia decir:
`[JsonProperty(PropertyName = "alias", NullValueHandling=NullValueHandling.Ignore)]
public String Alias { get; set; }`

**Comment by EcommerceBBVA** [comment]
Gracias por la observación, se ha corregido la sintaxis
